class PoliceOfficers {
  String userId,
      firstName,
      lastName,
      emailAddress,
      avatar,
      address,
      badgeId,
      phoneNumber,
      vehicleNumber,
      licencePlateNumber,
      state,
      district,
      station,
      totalRatings,
      totalRaters,
      onDuty;

  PoliceOfficers(
      this.userId,
      this.firstName,
      this.lastName,
      this.emailAddress,
      this.avatar,
      this.address,
      this.badgeId,
      this.phoneNumber,
      this.vehicleNumber,
      this.licencePlateNumber,
      this.state,
      this.district,
      this.station,
      this.totalRatings,
      this.totalRaters,
      this.onDuty);
}
